# [START functions_ci_cd_cloud_build]
steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "functions/helloworld"
  - name: "gcr.io/cloud-builders/npm"
    args: ["test"]
    dir: "functions/helloworld"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "helloGET",
        "--trigger-http",
        "--runtime",
        "nodejs12",
        "--entry-point",
        "helloGET",
      ]
    dir: "functions/helloworld"
# [END functions_ci_cd_cloud_build]
